version: '3.8'

services:
  database:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword12#
    volumes:
      - sqldata:/var/opt/mssql
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB
  app:
    container_name: bazarapp
    image: hristodobrevbazarcr.azurecr.io/bazar
    domainname: hdobrevbazar
    ports:
      - 80:80
    restart: on-failure

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: hristodobrevbazarsa
